### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by RicardoSilvestr**

### CODE REVIEW

**Review by targos — CHANGES_REQUESTED** [review]
This is a breaking change that we need to review

**Comment by targos** [comment]
@RicardoSilvestr Are you doing this update for a specific reason?

**Comment by RicardoSilvestr** [comment]
> @RicardoSilvestr Are you doing this update for a specific reason?

I was updating the dependencies of xrd-analysis and i saw that the update of eslint-plugin-jest to the version 27.1.1 was not allowed because of eslint-config. Since it is a breaking change i suggest close the pull request without merging this branch. For xrd-analysis I updated eslint-plugin-jest to the highest version allowed (26.4.6).

**Comment by targos** [comment]
You should remove `eslint-plugin-jest` from the dependencies of `xrd-analysis`. As a peer dependency, the correct version will be installed automatically.

**Pull request closed without merging**
